apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: ocp-{{ .Values.clusterName }}-cluster-secrets
spec:
  connection:
    address: "{{ .Values.connection.address }}"
  authentication:
    path: "{{ .Values.authentication.path }}"
    role: "{{ .Values.authentication.role }}"
    serviceAccount:
      name: "{{ .Values.authentication.serviceAccount.name }}"
  type: acl
  policy: |
    path "/secrets/ocp/allclusters/*" {
      capabilities = ["read"]
    }
    path "/secrets/ocp/cluster/{{ .Values.clusterName }}/*" {
      capabilities = ["read"]
    }
